#!/usr/bin/env ruby
#
require 'zfs/snap'
require 'zfs/snap/cli'

$script_name = File.basename(__FILE__)
$err_status = 0

cli = ZFS::Snap::CLI.new
datasets = cli.parse_opts(ARGV)
request = cli.option

if !request[:create].empty? && !datasets.empty?
  datasets.each do |dataset|
    snapshot = ZFS::Snap::Dataset.new(dataset, params: request[:create])
    snapshot.create(request) if snapshot.name
  end
elsif request[:destroy] && !datasets.empty?
  pattern = datasets.join('|')

  ZFS::Snap.scan(pattern).each do |snapshot|
    snapshot.destroy(request)
  end
elsif request[:expire]
  pattern = datasets.empty? ? '.*' : datasets.join('|')

  ZFS::Snap.scan(pattern).each do |snapshot|
    snapshot.destroy(request) if snapshot.expired?
  end
elsif request[:list]
  pattern = datasets.empty? ? '.*' : datasets.join('|')

  ZFS::Snap.scan(pattern).each do |snapshot|
    puts snapshot.name
  end
else
  cli.parse_opts('-h')
end

exit $err_status

# Local variables:
# Mode: enh-ruby-mode
# coding: utf-8-unix
# End:
